name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install for dependencies eucaifcon25
        run: npm ci
        working-directory: ./eucaifcon25

      - name: Install dependencies for infn_qc_workshop
        run: npm ci
        working-directory: ./infn_qc_workshop

      - name: Build eucaifcon25
        run: npm run build -- --base /${{github.event.repository.name}}/eucaifcon25/
        working-directory: ./eucaifcon25

      - name: Build infn_qc_workshop
        run: npm run build -- --base /${{github.event.repository.name}}/infn_qc_workshop/
        working-directory: ./infn_qc_workshop

      - name: Combine outputs
        run: |
          mkdir -p combined_dist/eucaifcon25
          mkdir -p combined_dist/infn_qc_workshop
          cp -r eucaifcon25/dist/* combined_dist/eucaifcon25/
          cp -r infn_qc_workshop/dist/* combined_dist/infn_qc_workshop/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: combined_dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
